/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GvText: typeof import('./../src/components/common/GvText.vue')['default']
    HolderOutlined: typeof import('@nancal-icon/icons-vue')['HolderOutlined']
    NButton: typeof import('n-designv3/es')['Button']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
